#! /bin/sh

IPaddress='PUT IP ADDRESS HERE'
remote_file='output_key.txt'
remote_host="peter@$IPaddress"
remote_crack_dir='/home/peter/Projects/crackPipe/fileBin'
local_dir='../outputs'
remote_password='PUT PASSWORD HERE'
no_file_error="scp: /home/peter/Projects/crackPipe/fileBin/\
output_key.txt: No such file or directory"
success=''

expect -c"
	spawn scp $remote_host:$remote_crack_dir/$remote_file $local_dir/
	expect \"password:\" {
		send -- \"$remote_password\r\"
	}
	expect {
	
		\"$no_file_error\" {
			exit 1
		}
		\"*100%*\" {
			exit 0
		}
	}
	expect eof
"

expect_return=$?
exit $expect_return
