#! /bin/sh

IPaddress=''
handshakeFile='handshake-01.cap'
BSSIDFile='targetBSSID.txt'
ESSIDFile='targetESSID.txt'
remote_host="peter@$IPaddress"
remote_crack_dir='/home/peter/Projects/crackPipe/fileBin'
remote_password=''
error_no_network="ssh: connect to host $IPaddress port 22: No route to host"
expect -c"
	spawn scp $handshakeFile $BSSIDFile $ESSIDFile $remote_host:$remote_crack_dir
	expect {
	
		\"password:\" { send -- \"$remote_password\r \" 
					expect \"targetESSID.txt*100%\" { exit 0 }
		}

		\"$error_no_network\" { exit 1 }

	}
	exit 1
"
expect_return_code=$?

# Exit with return code of expect
exit $expect_return_code
